.\" This is a man page for the libroman static library.
.
.\" Written by Bill Koester, Detroit Michigan USA, 12/2016.
.TH LIBROMAN 1 "11/07/2016" "(C) Pillar Technology Inc." "Bill Koester"
.
.SH NAME
libroman \- Convert roman numerals to/from integers
.
.SH SYNOPSIS
.B libroman
.
.SH DESCRIPTION
The
.B libroman
library converts to/from integers and roman numerals.

Roman numerals consist of the following letters: I, V, X, L, C, D, and M which mean one, five,
ten, fifty, hundred, five hundred and one thousand respectively.

An example would be "XIV" + "LX" = "LXXIV"

Numerals can be concatenated to form a larger numeral ("XX" + "II" = "XXII").

If a lesser numeral is put before a bigger it means subtraction of the lesser from the bigger ("IV"
means four, "CM" means ninehundred).

If the numeral is I, X or C you can't have more than three ("II" + "II" = "IV" not “IIII”).

If the numeral is V, L or D you can't have more than one ("D" + "D" = "M" not “DD”)

The maximum roman numeral is 3999 (MMMCMXCIX)
.
.SH AUTHOR
Bill Koester <bill.koester@pillartechnology.com
.
.SH SEE ALSO
intToRoman(1) romanToInt(1)
